
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbvxnapruffchikhrqrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndidnhuYXBydWZmY2hpa2hycXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MDIyOTgsImV4cCI6MjA2MzA3ODI5OH0.D4ZFSvFactaHtrhCDms7VF6yVJPO2PnOxUF_ugKU0FI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      debug: true, // Enable debug logs to help troubleshoot authentication issues
    },
  }
);
